/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TrackRouteImport } from './routes/track'
import { Route as StudioAccessRouteImport } from './routes/studio-access'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as OrderConfirmedRouteImport } from './routes/order-confirmed'
import { Route as NnStudio7f3a91RouteImport } from './routes/nn-studio-7f3a91'
import { Route as DesignersRouteImport } from './routes/designers'
import { Route as CustomOrderRouteImport } from './routes/custom-order'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PortfolioIndexRouteImport } from './routes/portfolio.index'
import { Route as PortfolioSlugRouteImport } from './routes/portfolio.$slug'
import { Route as DesignersIdRouteImport } from './routes/designers.$id'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated/profile'
import { Route as AuthenticatedOrdersRouteImport } from './routes/_authenticated/orders'
import { Route as AuthenticatedMessagesRouteImport } from './routes/_authenticated/messages'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedAtelierRouteImport } from './routes/_authenticated/atelier'
import { Route as AuthenticatedAppointmentsRouteImport } from './routes/_authenticated/appointments'
import { Route as AuthenticatedOrdersNewRouteImport } from './routes/_authenticated/orders.new'
import { Route as AuthenticatedOrdersIdRouteImport } from './routes/_authenticated/orders.$id'
import { Route as AuthenticatedAdminUsersRouteImport } from './routes/_authenticated/admin.users'
import { Route as AuthenticatedAdminStylesRouteImport } from './routes/_authenticated/admin.styles'
import { Route as AuthenticatedAdminServicesRouteImport } from './routes/_authenticated/admin.services'
import { Route as AuthenticatedAdminRequestsRouteImport } from './routes/_authenticated/admin.requests'
import { Route as AuthenticatedAdminPortalRouteImport } from './routes/_authenticated/admin.portal'
import { Route as AuthenticatedAdminRequestsIdRouteImport } from './routes/_authenticated/admin.requests.$id'

const TrackRoute = TrackRouteImport.update({
  id: '/track',
  path: '/track',
  getParentRoute: () => rootRouteImport,
} as any)
const StudioAccessRoute = StudioAccessRouteImport.update({
  id: '/studio-access',
  path: '/studio-access',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const OrderConfirmedRoute = OrderConfirmedRouteImport.update({
  id: '/order-confirmed',
  path: '/order-confirmed',
  getParentRoute: () => rootRouteImport,
} as any)
const NnStudio7f3a91Route = NnStudio7f3a91RouteImport.update({
  id: '/nn-studio-7f3a91',
  path: '/nn-studio-7f3a91',
  getParentRoute: () => rootRouteImport,
} as any)
const DesignersRoute = DesignersRouteImport.update({
  id: '/designers',
  path: '/designers',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomOrderRoute = CustomOrderRouteImport.update({
  id: '/custom-order',
  path: '/custom-order',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PortfolioIndexRoute = PortfolioIndexRouteImport.update({
  id: '/portfolio/',
  path: '/portfolio/',
  getParentRoute: () => rootRouteImport,
} as any)
const PortfolioSlugRoute = PortfolioSlugRouteImport.update({
  id: '/portfolio/$slug',
  path: '/portfolio/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const DesignersIdRoute = DesignersIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => DesignersRoute,
} as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedOrdersRoute = AuthenticatedOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMessagesRoute = AuthenticatedMessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAtelierRoute = AuthenticatedAtelierRouteImport.update({
  id: '/atelier',
  path: '/atelier',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAppointmentsRoute =
  AuthenticatedAppointmentsRouteImport.update({
    id: '/appointments',
    path: '/appointments',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedOrdersNewRoute = AuthenticatedOrdersNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AuthenticatedOrdersRoute,
} as any)
const AuthenticatedOrdersIdRoute = AuthenticatedOrdersIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AuthenticatedOrdersRoute,
} as any)
const AuthenticatedAdminUsersRoute = AuthenticatedAdminUsersRouteImport.update({
  id: '/admin/users',
  path: '/admin/users',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminStylesRoute =
  AuthenticatedAdminStylesRouteImport.update({
    id: '/admin/styles',
    path: '/admin/styles',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminServicesRoute =
  AuthenticatedAdminServicesRouteImport.update({
    id: '/admin/services',
    path: '/admin/services',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminRequestsRoute =
  AuthenticatedAdminRequestsRouteImport.update({
    id: '/admin/requests',
    path: '/admin/requests',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminPortalRoute =
  AuthenticatedAdminPortalRouteImport.update({
    id: '/admin/portal',
    path: '/admin/portal',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminRequestsIdRoute =
  AuthenticatedAdminRequestsIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => AuthenticatedAdminRequestsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/custom-order': typeof CustomOrderRoute
  '/designers': typeof DesignersRouteWithChildren
  '/nn-studio-7f3a91': typeof NnStudio7f3a91Route
  '/order-confirmed': typeof OrderConfirmedRoute
  '/services': typeof ServicesRoute
  '/studio-access': typeof StudioAccessRoute
  '/track': typeof TrackRoute
  '/appointments': typeof AuthenticatedAppointmentsRoute
  '/atelier': typeof AuthenticatedAtelierRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/messages': typeof AuthenticatedMessagesRoute
  '/orders': typeof AuthenticatedOrdersRouteWithChildren
  '/profile': typeof AuthenticatedProfileRoute
  '/designers/$id': typeof DesignersIdRoute
  '/portfolio/$slug': typeof PortfolioSlugRoute
  '/portfolio/': typeof PortfolioIndexRoute
  '/admin/portal': typeof AuthenticatedAdminPortalRoute
  '/admin/requests': typeof AuthenticatedAdminRequestsRouteWithChildren
  '/admin/services': typeof AuthenticatedAdminServicesRoute
  '/admin/styles': typeof AuthenticatedAdminStylesRoute
  '/admin/users': typeof AuthenticatedAdminUsersRoute
  '/orders/$id': typeof AuthenticatedOrdersIdRoute
  '/orders/new': typeof AuthenticatedOrdersNewRoute
  '/admin/requests/$id': typeof AuthenticatedAdminRequestsIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/custom-order': typeof CustomOrderRoute
  '/designers': typeof DesignersRouteWithChildren
  '/nn-studio-7f3a91': typeof NnStudio7f3a91Route
  '/order-confirmed': typeof OrderConfirmedRoute
  '/services': typeof ServicesRoute
  '/studio-access': typeof StudioAccessRoute
  '/track': typeof TrackRoute
  '/appointments': typeof AuthenticatedAppointmentsRoute
  '/atelier': typeof AuthenticatedAtelierRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/messages': typeof AuthenticatedMessagesRoute
  '/orders': typeof AuthenticatedOrdersRouteWithChildren
  '/profile': typeof AuthenticatedProfileRoute
  '/designers/$id': typeof DesignersIdRoute
  '/portfolio/$slug': typeof PortfolioSlugRoute
  '/portfolio': typeof PortfolioIndexRoute
  '/admin/portal': typeof AuthenticatedAdminPortalRoute
  '/admin/requests': typeof AuthenticatedAdminRequestsRouteWithChildren
  '/admin/services': typeof AuthenticatedAdminServicesRoute
  '/admin/styles': typeof AuthenticatedAdminStylesRoute
  '/admin/users': typeof AuthenticatedAdminUsersRoute
  '/orders/$id': typeof AuthenticatedOrdersIdRoute
  '/orders/new': typeof AuthenticatedOrdersNewRoute
  '/admin/requests/$id': typeof AuthenticatedAdminRequestsIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/custom-order': typeof CustomOrderRoute
  '/designers': typeof DesignersRouteWithChildren
  '/nn-studio-7f3a91': typeof NnStudio7f3a91Route
  '/order-confirmed': typeof OrderConfirmedRoute
  '/services': typeof ServicesRoute
  '/studio-access': typeof StudioAccessRoute
  '/track': typeof TrackRoute
  '/_authenticated/appointments': typeof AuthenticatedAppointmentsRoute
  '/_authenticated/atelier': typeof AuthenticatedAtelierRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/messages': typeof AuthenticatedMessagesRoute
  '/_authenticated/orders': typeof AuthenticatedOrdersRouteWithChildren
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/designers/$id': typeof DesignersIdRoute
  '/portfolio/$slug': typeof PortfolioSlugRoute
  '/portfolio/': typeof PortfolioIndexRoute
  '/_authenticated/admin/portal': typeof AuthenticatedAdminPortalRoute
  '/_authenticated/admin/requests': typeof AuthenticatedAdminRequestsRouteWithChildren
  '/_authenticated/admin/services': typeof AuthenticatedAdminServicesRoute
  '/_authenticated/admin/styles': typeof AuthenticatedAdminStylesRoute
  '/_authenticated/admin/users': typeof AuthenticatedAdminUsersRoute
  '/_authenticated/orders/$id': typeof AuthenticatedOrdersIdRoute
  '/_authenticated/orders/new': typeof AuthenticatedOrdersNewRoute
  '/_authenticated/admin/requests/$id': typeof AuthenticatedAdminRequestsIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/custom-order'
    | '/designers'
    | '/nn-studio-7f3a91'
    | '/order-confirmed'
    | '/services'
    | '/studio-access'
    | '/track'
    | '/appointments'
    | '/atelier'
    | '/dashboard'
    | '/messages'
    | '/orders'
    | '/profile'
    | '/designers/$id'
    | '/portfolio/$slug'
    | '/portfolio/'
    | '/admin/portal'
    | '/admin/requests'
    | '/admin/services'
    | '/admin/styles'
    | '/admin/users'
    | '/orders/$id'
    | '/orders/new'
    | '/admin/requests/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/custom-order'
    | '/designers'
    | '/nn-studio-7f3a91'
    | '/order-confirmed'
    | '/services'
    | '/studio-access'
    | '/track'
    | '/appointments'
    | '/atelier'
    | '/dashboard'
    | '/messages'
    | '/orders'
    | '/profile'
    | '/designers/$id'
    | '/portfolio/$slug'
    | '/portfolio'
    | '/admin/portal'
    | '/admin/requests'
    | '/admin/services'
    | '/admin/styles'
    | '/admin/users'
    | '/orders/$id'
    | '/orders/new'
    | '/admin/requests/$id'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/custom-order'
    | '/designers'
    | '/nn-studio-7f3a91'
    | '/order-confirmed'
    | '/services'
    | '/studio-access'
    | '/track'
    | '/_authenticated/appointments'
    | '/_authenticated/atelier'
    | '/_authenticated/dashboard'
    | '/_authenticated/messages'
    | '/_authenticated/orders'
    | '/_authenticated/profile'
    | '/designers/$id'
    | '/portfolio/$slug'
    | '/portfolio/'
    | '/_authenticated/admin/portal'
    | '/_authenticated/admin/requests'
    | '/_authenticated/admin/services'
    | '/_authenticated/admin/styles'
    | '/_authenticated/admin/users'
    | '/_authenticated/orders/$id'
    | '/_authenticated/orders/new'
    | '/_authenticated/admin/requests/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  CustomOrderRoute: typeof CustomOrderRoute
  DesignersRoute: typeof DesignersRouteWithChildren
  NnStudio7f3a91Route: typeof NnStudio7f3a91Route
  OrderConfirmedRoute: typeof OrderConfirmedRoute
  ServicesRoute: typeof ServicesRoute
  StudioAccessRoute: typeof StudioAccessRoute
  TrackRoute: typeof TrackRoute
  PortfolioSlugRoute: typeof PortfolioSlugRoute
  PortfolioIndexRoute: typeof PortfolioIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/track': {
      id: '/track'
      path: '/track'
      fullPath: '/track'
      preLoaderRoute: typeof TrackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/studio-access': {
      id: '/studio-access'
      path: '/studio-access'
      fullPath: '/studio-access'
      preLoaderRoute: typeof StudioAccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/order-confirmed': {
      id: '/order-confirmed'
      path: '/order-confirmed'
      fullPath: '/order-confirmed'
      preLoaderRoute: typeof OrderConfirmedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nn-studio-7f3a91': {
      id: '/nn-studio-7f3a91'
      path: '/nn-studio-7f3a91'
      fullPath: '/nn-studio-7f3a91'
      preLoaderRoute: typeof NnStudio7f3a91RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/designers': {
      id: '/designers'
      path: '/designers'
      fullPath: '/designers'
      preLoaderRoute: typeof DesignersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/custom-order': {
      id: '/custom-order'
      path: '/custom-order'
      fullPath: '/custom-order'
      preLoaderRoute: typeof CustomOrderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portfolio/': {
      id: '/portfolio/'
      path: '/portfolio'
      fullPath: '/portfolio/'
      preLoaderRoute: typeof PortfolioIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portfolio/$slug': {
      id: '/portfolio/$slug'
      path: '/portfolio/$slug'
      fullPath: '/portfolio/$slug'
      preLoaderRoute: typeof PortfolioSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/designers/$id': {
      id: '/designers/$id'
      path: '/$id'
      fullPath: '/designers/$id'
      preLoaderRoute: typeof DesignersIdRouteImport
      parentRoute: typeof DesignersRoute
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/orders': {
      id: '/_authenticated/orders'
      path: '/orders'
      fullPath: '/orders'
      preLoaderRoute: typeof AuthenticatedOrdersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/messages': {
      id: '/_authenticated/messages'
      path: '/messages'
      fullPath: '/messages'
      preLoaderRoute: typeof AuthenticatedMessagesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/atelier': {
      id: '/_authenticated/atelier'
      path: '/atelier'
      fullPath: '/atelier'
      preLoaderRoute: typeof AuthenticatedAtelierRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/appointments': {
      id: '/_authenticated/appointments'
      path: '/appointments'
      fullPath: '/appointments'
      preLoaderRoute: typeof AuthenticatedAppointmentsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/orders/new': {
      id: '/_authenticated/orders/new'
      path: '/new'
      fullPath: '/orders/new'
      preLoaderRoute: typeof AuthenticatedOrdersNewRouteImport
      parentRoute: typeof AuthenticatedOrdersRoute
    }
    '/_authenticated/orders/$id': {
      id: '/_authenticated/orders/$id'
      path: '/$id'
      fullPath: '/orders/$id'
      preLoaderRoute: typeof AuthenticatedOrdersIdRouteImport
      parentRoute: typeof AuthenticatedOrdersRoute
    }
    '/_authenticated/admin/users': {
      id: '/_authenticated/admin/users'
      path: '/admin/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AuthenticatedAdminUsersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/styles': {
      id: '/_authenticated/admin/styles'
      path: '/admin/styles'
      fullPath: '/admin/styles'
      preLoaderRoute: typeof AuthenticatedAdminStylesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/services': {
      id: '/_authenticated/admin/services'
      path: '/admin/services'
      fullPath: '/admin/services'
      preLoaderRoute: typeof AuthenticatedAdminServicesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/requests': {
      id: '/_authenticated/admin/requests'
      path: '/admin/requests'
      fullPath: '/admin/requests'
      preLoaderRoute: typeof AuthenticatedAdminRequestsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/portal': {
      id: '/_authenticated/admin/portal'
      path: '/admin/portal'
      fullPath: '/admin/portal'
      preLoaderRoute: typeof AuthenticatedAdminPortalRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/requests/$id': {
      id: '/_authenticated/admin/requests/$id'
      path: '/$id'
      fullPath: '/admin/requests/$id'
      preLoaderRoute: typeof AuthenticatedAdminRequestsIdRouteImport
      parentRoute: typeof AuthenticatedAdminRequestsRoute
    }
  }
}

interface AuthenticatedOrdersRouteChildren {
  AuthenticatedOrdersIdRoute: typeof AuthenticatedOrdersIdRoute
  AuthenticatedOrdersNewRoute: typeof AuthenticatedOrdersNewRoute
}

const AuthenticatedOrdersRouteChildren: AuthenticatedOrdersRouteChildren = {
  AuthenticatedOrdersIdRoute: AuthenticatedOrdersIdRoute,
  AuthenticatedOrdersNewRoute: AuthenticatedOrdersNewRoute,
}

const AuthenticatedOrdersRouteWithChildren =
  AuthenticatedOrdersRoute._addFileChildren(AuthenticatedOrdersRouteChildren)

interface AuthenticatedAdminRequestsRouteChildren {
  AuthenticatedAdminRequestsIdRoute: typeof AuthenticatedAdminRequestsIdRoute
}

const AuthenticatedAdminRequestsRouteChildren: AuthenticatedAdminRequestsRouteChildren =
  {
    AuthenticatedAdminRequestsIdRoute: AuthenticatedAdminRequestsIdRoute,
  }

const AuthenticatedAdminRequestsRouteWithChildren =
  AuthenticatedAdminRequestsRoute._addFileChildren(
    AuthenticatedAdminRequestsRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAppointmentsRoute: typeof AuthenticatedAppointmentsRoute
  AuthenticatedAtelierRoute: typeof AuthenticatedAtelierRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedMessagesRoute: typeof AuthenticatedMessagesRoute
  AuthenticatedOrdersRoute: typeof AuthenticatedOrdersRouteWithChildren
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
  AuthenticatedAdminPortalRoute: typeof AuthenticatedAdminPortalRoute
  AuthenticatedAdminRequestsRoute: typeof AuthenticatedAdminRequestsRouteWithChildren
  AuthenticatedAdminServicesRoute: typeof AuthenticatedAdminServicesRoute
  AuthenticatedAdminStylesRoute: typeof AuthenticatedAdminStylesRoute
  AuthenticatedAdminUsersRoute: typeof AuthenticatedAdminUsersRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAppointmentsRoute: AuthenticatedAppointmentsRoute,
  AuthenticatedAtelierRoute: AuthenticatedAtelierRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedMessagesRoute: AuthenticatedMessagesRoute,
  AuthenticatedOrdersRoute: AuthenticatedOrdersRouteWithChildren,
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
  AuthenticatedAdminPortalRoute: AuthenticatedAdminPortalRoute,
  AuthenticatedAdminRequestsRoute: AuthenticatedAdminRequestsRouteWithChildren,
  AuthenticatedAdminServicesRoute: AuthenticatedAdminServicesRoute,
  AuthenticatedAdminStylesRoute: AuthenticatedAdminStylesRoute,
  AuthenticatedAdminUsersRoute: AuthenticatedAdminUsersRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface DesignersRouteChildren {
  DesignersIdRoute: typeof DesignersIdRoute
}

const DesignersRouteChildren: DesignersRouteChildren = {
  DesignersIdRoute: DesignersIdRoute,
}

const DesignersRouteWithChildren = DesignersRoute._addFileChildren(
  DesignersRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  CustomOrderRoute: CustomOrderRoute,
  DesignersRoute: DesignersRouteWithChildren,
  NnStudio7f3a91Route: NnStudio7f3a91Route,
  OrderConfirmedRoute: OrderConfirmedRoute,
  ServicesRoute: ServicesRoute,
  StudioAccessRoute: StudioAccessRoute,
  TrackRoute: TrackRoute,
  PortfolioSlugRoute: PortfolioSlugRoute,
  PortfolioIndexRoute: PortfolioIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
