// This file is automatically generated. Do not edit it directly.
import { createMiddleware } from "@tanstack/react-start";
import { getRequest } from "@tanstack/react-start/server";
import { createClient } from "@supabase/supabase-js";
import type { Database } from "./types";

function isNewSupabaseApiKey(value: string): boolean {
  return value.startsWith("sb_publishable_") || value.startsWith("sb_secret_");
}

function createSupabaseFetch(supabaseKey: string): typeof fetch {
  return (input, init) => {
    const headers = new Headers(
      typeof Request !== "undefined" && input instanceof Request ? input.headers : undefined,
    );

    if (init?.headers) {
      new Headers(init.headers).forEach((value, key) => headers.set(key, value));
    }

    // New Supabase API keys are opaque strings, not bearer JWTs.
    if (
      isNewSupabaseApiKey(supabaseKey) &&
      headers.get("Authorization") === `Bearer ${supabaseKey}`
    ) {
      headers.delete("Authorization");
    }

    headers.set("apikey", supabaseKey);
    return fetch(input, { ...init, headers });
  };
}

export const requireSupabaseAuth = createMiddleware({ type: "function" }).server(
  async ({ next }) => {
    const SUPABASE_URL = process.env.SUPABASE_URL || process.env.VITE_SUPABASE_URL;
    const SUPABASE_PUBLISHABLE_KEY =
      process.env.SUPABASE_PUBLISHABLE_KEY || process.env.VITE_SUPABASE_PUBLISHABLE_KEY;

    const request = getRequest();

    // 1. Check Supabase bearer token if provided
    const authHeader = request?.headers?.get("authorization");
    if (
      authHeader &&
      authHeader.startsWith("Bearer ") &&
      SUPABASE_URL &&
      SUPABASE_PUBLISHABLE_KEY
    ) {
      const token = authHeader.replace("Bearer ", "").trim();
      if (token && token.split(".").length === 3) {
        try {
          const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
            global: {
              fetch: createSupabaseFetch(SUPABASE_PUBLISHABLE_KEY),
              headers: {
                Authorization: `Bearer ${token}`,
              },
            },
            auth: {
              storage: undefined,
              persistSession: false,
              autoRefreshToken: false,
            },
          });

          const { data, error } = await supabase.auth.getClaims(token);
          if (!error && data?.claims?.sub) {
            return next({
              context: {
                supabase,
                userId: data.claims.sub,
                claims: data.claims,
              },
            });
          }
        } catch {
          // fall through to Clerk authentication
        }
      }
    }

    // 2. Check Clerk session authentication
    try {
      const { auth: getClerkAuth, clerkClient: getClerkClient } =
        await import("@clerk/tanstack-react-start/server");
      const clerkAuth = await getClerkAuth();
      if (clerkAuth?.userId) {
        let email = "";
        try {
          const client = getClerkClient();
          const user = await client.users.getUser(clerkAuth.userId);
          email =
            user.emailAddresses.find((e) => e.id === user.primaryEmailAddressId)?.emailAddress ||
            user.emailAddresses[0]?.emailAddress ||
            "";
        } catch (e) {
          console.warn("[Clerk] Failed to fetch user email:", e);
        }

        const supabase = createClient<Database>(
          SUPABASE_URL || "https://placeholder.supabase.co",
          SUPABASE_PUBLISHABLE_KEY || "placeholder-key",
          {
            global: {
              fetch: createSupabaseFetch(SUPABASE_PUBLISHABLE_KEY || "placeholder-key"),
            },
            auth: {
              storage: undefined,
              persistSession: false,
              autoRefreshToken: false,
            },
          },
        );

        // eslint-disable-next-line @typescript-eslint/no-explicit-any
        return (next as any)({
          context: {
            supabase,
            userId: clerkAuth.userId,
            claims: { sub: clerkAuth.userId, email },
          },
        });
      }
    } catch (e) {
      console.warn("[AuthMiddleware] Clerk auth check skipped:", e);
    }

    throw new Error("Unauthorized: Please sign in to continue");
  },
);
